create database if not exists route_du_rhum;

DROP TABLE IF EXISTS P02_skipper;
DROP TABLE IF EXISTS P02_bateau;
DROP TABLE IF EXISTS P02_resultat;

CREATE TABLE P02_skipper(
  skipper_id SERIAL PRIMARY KEY,
  skipper_nom VARCHAR(40) NOT NULL,
  skipper_prenom VARCHAR(40) NOT NULL,
  skipper_age INTEGER NOT NULL,
  skipper_sexe VARCHAR(10) CHECK (skipper_sexe IN('Homme','Femme')),
  skipper_nationnalite VARCHAR(20) NOT NULL
);

INSERT INTO P02_skipper(skipper_id, skipper_nom, skipper_prenom, skipper_age, skipper_sexe, skipper_nationnalite) VALUES
(DEFAULT,'CAUDRELIER', 'Charles' ,48,'Homme', 'Française'),
(DEFAULT,'GABART', 'François' ,39,'Homme', 'Française'),
(DEFAULT,'COVILLE', 'Thomas' ,54,'Homme', 'Française'),
(DEFAULT,'JOYON', 'Francis' ,66,'Homme', 'Française'),
(DEFAULT,'LE BLEVEC', 'Yves' ,57,'Homme', 'Française'),
(DEFAULT,'LE VAILLANT', 'Arthur' ,34,'Homme', 'Française'),
(DEFAULT,'LE ROUX', 'Erwan' ,48,'Homme', 'Française'),
(DEFAULT,'VLAMYNCK', 'Quentin' ,30,'Homme', 'Française'),
(DEFAULT,'LE CLÉAC''H', 'Armel' ,45,'Homme', 'Française'),
(DEFAULT,'ROGUES', 'Sébastien' ,36,'Homme', 'Française'),
(DEFAULT,'RUYANT', 'Thomas' ,41,'Homme', 'Française'),
(DEFAULT,'PERON', 'Eric' ,41,'Homme', 'Française'),
(DEFAULT,'DALIN', 'Charlie' ,38,'Homme', 'Française'),
(DEFAULT,'BEYOU', 'Jérémie' ,46,'Homme', 'Française'),
(DEFAULT,'ESCOFFIER', 'Kevin' ,42,'Homme', 'Française'),
(DEFAULT,'TRIPON', 'Armel' ,47,'Homme', 'Française'),
(DEFAULT,'SOREL', 'Maxime' ,36,'Homme', 'Française'),
(DEFAULT,'MEILHAT', 'Paul' ,40,'Homme', 'Française'),
(DEFAULT,'METTRAUX', 'Justine' ,36,'Femme', 'Suisse'),
(DEFAULT,'DUTREUX', 'Benjamin' ,32,'Homme', 'Française'),
(DEFAULT,'JOSCHKE', 'Isabelle' ,45,'Femme', 'Allemande'),
(DEFAULT,'ATTANASIO', 'Romain' ,45,'Homme', 'Française'),
(DEFAULT,'MARSSET', 'Sébastien' ,37,'Homme', 'Française'),
(DEFAULT,'HARE', 'Pip' ,48,'Femme', 'Anglaise'),
(DEFAULT,'LAMIRÉ', 'Gilles' ,52,'Homme', 'Française'),
(DEFAULT,'LE TURQUAIS', 'Tanguy' ,33,'Homme', 'Française'),
(DEFAULT,'HARAYDA', 'James' ,24,'Homme', 'Anglaise'),
(DEFAULT,'FERRE', 'Benjamin' ,32,'Homme', 'Française'),
(DEFAULT,'PEDOTE', 'Giancarlo' ,46,'Homme', 'Italienne'),
(DEFAULT,'BOISSIERES', 'Arnaud' ,50,'Homme', 'Française'),
(DEFAULT,'COLMAN', 'Conrad' ,38,'Homme', 'Néo-Zélandaise'),
(DEFAULT,'BESTAVEN', 'Yannick' ,49,'Homme', 'Française'),
(DEFAULT,'TROUSSEL', 'Nicolas' ,48,'Homme', 'Française'),
(DEFAULT,'ROURA', 'Alan' ,29,'Homme', 'Suisse'),
(DEFAULT,'RICHOMME', 'Yoann' ,39,'Homme', 'Française'),
(DEFAULT,'BECCARIA', 'Ambrogio' ,31,'Homme', 'Française'),
(DEFAULT,'CORNIC', 'Antoine' ,42,'Homme', 'Française'),
(DEFAULT,'DOUGUET', 'Corentin' ,48,'Homme', 'Française'),
(DEFAULT,'BELLION', 'Eric' ,46,'Homme', 'Française'),
(DEFAULT,'HERRMANN', 'Boris' ,41,'Homme', 'Allemande'),
(DEFAULT,'KOSTER', 'Simon' ,34,'Homme', 'Suisse'),
(DEFAULT,'SOUDEE', 'Guirec' ,30,'Homme', 'Française'),
(DEFAULT,'CARPENTIER', 'Antoine' ,47,'Homme', 'Française'),
(DEFAULT,'MACAIRE', 'Xavier' ,41,'Homme', 'Française'),
(DEFAULT,'WEÖRES', 'Szabolcs' ,49,'Homme', 'hongroise'),
(DEFAULT,'BERRY', 'LUKE' ,36,'Homme', 'Française'),
(DEFAULT,'DUC', 'Louis' ,39,'Homme', 'Française'),
(DEFAULT,'BONA', 'Alberto' ,36,'Homme', 'Italienne'),
(DEFAULT,'PILLIARD', 'Romain' ,47,'Homme', 'Française'),
(DEFAULT,'LE PAPE', 'Martin' ,34,'Homme', 'Française'),
(DEFAULT,'DAVIES', 'Samantha' ,48,'Femme', 'Anglaise'),
(DEFAULT,'ESCOFFIER', 'Loïc' ,41,'Homme', 'Française'),
(DEFAULT,'JOURDAIN', 'Roland' ,58,'Homme', 'Française'),
(DEFAULT,'XU', 'Jingkun' ,33,'Homme', 'Chinoise'),
(DEFAULT,'TRÉHIN', 'Axel' ,34,'Homme', 'Française'),
(DEFAULT,'DE PAVANT', 'Kito' ,61,'Homme', 'Française'),
(DEFAULT,'COUSIN', 'Manuel' ,55,'Homme', 'Française'),
(DEFAULT,'LE ROCH', 'Emmanuel' ,49,'Homme', 'Française'),
(DEFAULT,'DICK', 'Jean-Pierre' ,57,'Homme', 'Française'),
(DEFAULT,'LIPINSKI', 'Ian' ,41,'Homme', 'Française'),
(DEFAULT,'MEHRAN', 'Alex' ,63,'Homme', 'Américaine'),
(DEFAULT,'GUILLEMOT', 'Marc' ,63,'Homme', 'Française'),
(DEFAULT,'GUIFFANT', 'François' ,49,'Homme', 'Française'),
(DEFAULT,'MABIRE', 'Halvard' ,66,'Homme', 'Française'),
(DEFAULT,'D''ESTAIS', 'Nicolas' ,31,'Homme', 'Française'),
(DEFAULT,'MATHELIN-MOREAUX', 'William' ,29,'Homme', 'Française'),
(DEFAULT,'HEER', 'Oliver' ,34,'Homme', 'Suisse'),
(DEFAULT,'BONNIER', 'Jules' ,27,'Homme', 'Française'),
(DEFAULT,'HULIN', 'Baptiste' ,25,'Homme', 'Française'),
(DEFAULT,'CHATEAU', 'Cédric' ,45,'Homme', 'Française'),
(DEFAULT,'LEPESQUEUX', 'Marc' ,54,'Homme', 'Française'),
(DEFAULT,'FORNARO', 'Andrea' ,45,'Homme', 'Italienne'),
(DEFAULT,'CHAPALAIN', 'Gwen' ,53,'Homme', 'Française'),
(DEFAULT,'DARAMY', 'Jean-Baptiste' ,41,'Homme', 'Française'),
(DEFAULT,'LE VOURCH', 'Didier', 23, 'Homme', 'Française'),
(DEFAULT,'LE BORGNE', 'Kieran', 24, 'Homme', 'Française'),
(DEFAULT,'SEPHO', 'Rodolphe', 36, 'Homme', 'Française'),
(DEFAULT,'PAYEN', 'Fabrice', 54, 'Homme', 'Française'),
(DEFAULT,'THURET', 'Stan', 35, 'Homme', 'Française'),
(DEFAULT,'CASENAVE-PÉRÉ', 'Pierre', 23, 'Homme', 'Française'),
(DEFAULT,'POUPON', 'Philippe', 68 , 'Homme', 'Française'),
(DEFAULT,'HOCHEDE', 'Etienne', 66 , 'Homme', 'Française'),
(DEFAULT,'ATTWELL', 'Pierre-Louis', 26 , 'Homme', 'Française'),
(DEFAULT,'CLAVEAU', 'Mathieu', 34 , 'Homme', 'Française'),
(DEFAULT,'LEONARD', 'Greg', 49 , 'Homme', 'Américaine'),
(DEFAULT,'ROUGER', 'Nicolas', 43 , 'Homme', 'Française'),
(DEFAULT,'JOST', 'Victor', 27 , 'Homme', 'Française'),
(DEFAULT,'CHABAUD', 'Catherine', 60 , 'Femme', 'Française'),
(DEFAULT,'URSAULT POUPON', 'Morgane', 36 , 'Femme', 'Française'),
(DEFAULT,'CLERTON', 'Wilfrid' , 51  , 'Homme' , 'Française' ) ,
(DEFAULT,'BOUVET', 'Franz' , 62  , 'Homme' , 'Française' ) ,
(DEFAULT,'GUEGUEN' , 'Florian' , 30  , 'Homme' , 'Française' ) ,
(DEFAULT,'CAUWE' , 'Maxime' , 38  , 'Homme' , 'Française' ) ,
(DEFAULT,'BISSAINTE' , 'Willy' , 52  , 'Homme' , 'Française' ) ,
(DEFAULT,'FACON' , 'Anatole' , 22  , 'Homme' , 'Française' ) ,
(DEFAULT,'CAPELLE' , 'Charlie' , 67  , 'Homme' , 'Française' ) ,
(DEFAULT,'BOGRAND' , 'Christophe' ,59   , 'Homme' , 'Française' ) ,
(DEFAULT,'LURTON' , 'Thomas' , 25  , 'Homme' , 'Française' ) ,
(DEFAULT,'ETHEIMER' , 'Laurent' , 60  , 'Homme' , 'Française' ) ,
(DEFAULT,'THOMAS' , 'Hervé' , 56  , 'Homme' , 'Française' ) ,
(DEFAULT,'COLUBI' , 'Gilles' , 63  , 'Homme' , 'Française' ) ,
(DEFAULT,'NEMSGUERN' , 'Olivier' , 49  , 'Homme' , 'Française' ) ,
(DEFAULT,'PIPEROL' , 'Keni' , 26  , 'Homme' , 'Française' ) ,
(DEFAULT,'PRONIER' , 'Guy' , 59  , 'Homme' , 'Française' ) ,
(DEFAULT,'GERIN' , 'Remy' , 60  , 'Homme' , 'Française' ) ,
(DEFAULT,'GENNARI' , 'Fabio' , 30  , 'Homme' , 'Française' ) ,
(DEFAULT,'PENNARUN' , 'Arnaud' , 50  , 'Homme' , 'Française' ) ,
(DEFAULT,'ECALARD' , 'Daniel' ,  66  , 'Homme' , 'Française' ) ,
(DEFAULT,'BIARD' , 'Jean-Sébastien' , 51   , 'Homme' , 'Française' ) ,
(DEFAULT,'DUCOSSON' , 'David' , 50   , 'Homme' , 'Française' );


CREATE TABLE IF NOT EXISTS P02_bateau(
bateau_id  SERIAL PRIMARY KEY,
bateau_nom VARCHAR(60) NOT NULL,
bateau_date INTEGER NOT NULL, -- INT car on a pas la date complete mais juste l'année
bateau_architecte VARCHAR(40) NOT NULL,
bateau_classe VARCHAR(20) CHECK (bateau_classe IN('Ultim 32/23','Ocean Fifty','IMOCA','Class40','Rhum Multi','Rhum Mono'))
);


(DEFAULT, 'Maxi Edmond de Rothschild ', 2017, 'Team Verdier', 'Ultim 32/23'),
(DEFAULT, 'SVR-LAZARTIGUE', 2021, 'VPLP', 'Ultim 32/23'),
(DEFAULT, 'Sodebo Ultim 3', 2019, 'Sodebo Design', 'Ultim 32/23'),
(DEFAULT, 'IDEC Sport', 2006, 'VPLP DESIGN', 'Ultim 32/23'),
(DEFAULT, 'ACTUAL ULTIM 3', 2015, 'VPLP DESIGN', 'Ultim 32/23'),
(DEFAULT, 'MIEUX', 2012, 'VPLP', 'Ultim 32/23'),
(DEFAULT, 'KOESIO', 2020, 'VPLP', 'Ocean Fifty'),
(DEFAULT, 'ARKEMA', 2020, 'NEYHOUSSER', 'Ocean Fifty'),
(DEFAULT, 'MAXI BANQUE POPULAIRE XI', 2021, 'VPLP DESIGN', 'Ultim 32/23'),
(DEFAULT, 'Primonial', 2009, 'Guillaume VERDIER', 'Ocean Fifty'),
(DEFAULT, 'LinkedOut', 2019, 'Guillaume VERDIER', 'IMOCA'),
(DEFAULT, 'KOMILFO', 2009, 'Nigel', 'Ocean Fifty'),
(DEFAULT, 'APIVIA', 2019, 'Guillaume VERDIER', 'IMOCA'),
(DEFAULT, 'CHARAL', 2021, 'Sam MANUARD', 'IMOCA'),
(DEFAULT, 'Holcim - PRB', 2022, 'Guillaume VERDIER', 'IMOCA'),
(DEFAULT, 'Les P''tits Doudous', 2013, 'Romaric NEYHOUSSER', 'Ocean Fifty'),
(DEFAULT, 'V and B - Monbana - Mayenne', 2022, 'Guillaume VERDIER', 'IMOCA'),
(DEFAULT, 'BIOTHERM', 2022, 'Guillaume Verdier', 'IMOCA'),
(DEFAULT, 'TEAMWORK.NET', 2018, 'VPLP', 'IMOCA'),
(DEFAULT, 'Guyot environnement - Water Family ', 2016, 'VPLP', 'IMOCA'),
(DEFAULT, 'MACSF', 2007, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'Fortinet - Best Western', 2015, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'Mon Courtier Energie - Cap Agir Ensemble', 2006, 'Farr Yacht Design', 'IMOCA'),
(DEFAULT, 'Medallia', 2015, 'Verdier', 'IMOCA'),
(DEFAULT, 'GROUPE GCA-1001 SOURIRES', 2009, 'VPLP DESIGN', 'Ocean Fifty'),
(DEFAULT, 'LAZARE', 2008, 'Finot-Conq', 'IMOCA'),
(DEFAULT, 'Gentoo Sailing Team', 2007, 'FINOT-CONQ', 'IMOCA'),
(DEFAULT, 'Monnoyeur - Duo for a job', 2011, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'PRYSMIAN GROUP', 2015, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'La Mie Câline', 2010, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'Imagine', 2007, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'Maître CoQ V', 2022, 'Guillaume VERDIER', 'IMOCA'),
(DEFAULT, 'CORUM L''ÉPARGNE', 2019, 'Juan KOUYOUMDJIAN', 'IMOCA'),
(DEFAULT, 'Hublot', 2019, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'Paprec Arkéa', 2022, 'Marc Lombard Yacht Design', 'Class40'),
(DEFAULT, 'ALLAGRANDE PIRELLI', 2022, 'Gianluca Guelfi', 'Class40'),
(DEFAULT, 'HUMAN Immobilier', 2006, 'OWEN CLARKE DESIGN', 'IMOCA'),
(DEFAULT, 'QUEGUINER - INNOVEO', 2022, 'Marc Lombard Yacht Design', 'Class40'),
(DEFAULT, 'COMMEUNSEULHOMME Powered by Altavia', 2006, 'Farr Yacht Design', 'IMOCA'),
(DEFAULT, 'Malizia - Seaexplorer', 2022, 'VPLP DESIGN', 'IMOCA'),
(DEFAULT, 'Banque du Leman', 2019, 'Sam MANUARD', 'Class40'),
(DEFAULT, 'FREELANCE.COM', 2007, 'PLAN FARR', 'IMOCA'),
(DEFAULT, 'Redman', 2020, 'Sam MANUARD', 'Class40'),
(DEFAULT, 'Groupe SNEF', 2022, 'Guillaume VERDIER', 'Class40'),
(DEFAULT, 'Szabi Racing', 2007, 'OWEN CLARKE DESIGN', 'IMOCA'),
(DEFAULT, 'Lamotte - Module Création', 2022, 'Sam MANUARD', 'Class40'),
(DEFAULT, 'Fives - Lantana Environnement', 200, 'Farr Yacht Design', 'IMOCA'),
(DEFAULT, 'IBSA', 2022, 'Sam MANUARD', 'Class40'),
(DEFAULT, 'Use It Again! by Extia', 2003, 'Benoit CABARET', 'Ultim 32/23'),
(DEFAULT, 'Fondation Stargardt', 2022, 'VPLP DESIGN', 'Class40'),
(DEFAULT, 'INITIATIVES COEUR', 2021, 'Sam MANUARD', 'IMOCA'),
(DEFAULT, 'LODIGROUP', 2022, 'Christophe BARREAU', 'Rhum Multi'),
(DEFAULT, 'We Explore', 2022, 'VPLP DESIGN', 'Rhum Multi'),
(DEFAULT, 'China Dream•Haikou', 2007, 'FINOT-COQ', 'IMOCA'),
(DEFAULT, 'Project Rescue Ocean', 2021, 'David RAISON', 'Class40'),
(DEFAULT, 'HBF - Reforest''Action', 2014, 'Guillaume VERDIER', 'Class40'),
(DEFAULT, 'Groupe SÉTIN', 2007, 'Bruce FARR', 'IMOCA'),
(DEFAULT, 'Edenred', 2021, 'Sam MANUARD', 'Class40'),
(DEFAULT, 'Notre Méditerranée - Ville de Nice', 2010, 'Guillaume VERDIER', 'Rhum Mono'),
(DEFAULT, 'CRÉDIT MUTUEL', 2018, 'David RAISON', 'Class40'),
(DEFAULT, 'Polka Dot', 2018, 'Marc Lombard Yacht Design', 'Class40'),
(DEFAULT, 'METAROM MG5', 2021, 'Christophe Barreau', 'Rhum Multi'),
(DEFAULT, 'Kattan', 2004, 'Marc Lombard Yacht Design', 'IMOCA'),
(DEFAULT, 'GDD', 2021, 'Christophe Barreau', 'Rhum Multi'),
(DEFAULT,'HappyVore - Café Joyeux' , 2021 , 'VPLP' , 'Class40' ) ,
(DEFAULT,'Dékuple' , 2022 , ' VPLP DESIGN' , 'Class40' ) ,
(DEFAULT,'Oliver Heer Ocean Racing' , 2008 , 'Farr Yacht Design' , 'IMOCA' ) ,
(DEFAULT,'Nestenn - Entrepreneurs pour la Planète' , 2018 , 'Sam MANUARD' , 'Class40' ) ,
(DEFAULT,'Parenthèses de Vies' ,2017, 'Guillaume VERDIER' , 'Class40' ) ,
(DEFAULT,'SOGESTRAN - SEAFRIGO' , 2021 , 'Guillaume VERDIER' , 'Class40' ) ,
(DEFAULT,'CURIUM life forward' , 2022 , 'Marc Lombard Yacht Design' , 'Class40' ) ,
(DEFAULT,'INFLUENCE' , 2021 , 'VPLP DESIGN' , 'Class40' ) ,
(DEFAULT,'Guyader - Savéol' , 2020 , 'Christophe BARREAU' , 'Rhum Multi' ) ,
(DEFAULT,'Chocolats Paries - Screb' , 2013 , 'Sam MANUARD' , 'Class40' ) ,
(DEFAULT,'VICITAN' , 2014 , 'Sam MANUARD' , 'Class40' ) ,
(DEFAULT,'Recycleurs Bretons' , 2009 , 'Guillaume VERDIER' , 'Class40' ) ,
(DEFAULT,'Rêve de Large - Region Guadeloupe' , 2007 , 'Owen Clarke design' , 'IMOCA' ) ,
(DEFAULT,'Ille et Vilaine Cap vers l''inclusion' , 1987 , 'Nigel IRENS' , 'Rhum Multi' ) ,
(DEFAULT,'EVERIAL' , 2022 , 'Guillaume VERDIER' , 'Class40' ) ,
(DEFAULT,'Legallais' , 2015 , 'Sam MANUARD' , 'Class40' ) ,
(DEFAULT,'Flo' , 1990 , 'VPLP' , 'Rhum Multi' ) ,
(DEFAULT,'PiR2' , 1983 , 'Sylvestre LANGEVIN' , 'Rhum Multi' ) ,
(DEFAULT,'VOGUE AVEC UN CROHN' , 2014 , 'Fino-Conq' , 'Class40' ) ,
(DEFAULT,'Prendre la mer, Agir pour la Forêt' , 2008 , 'Marc Lombard Yacht Design' , 'Class40' ) ,
(DEFAULT,'Kite' , 2015 , 'Sam MANUARD' , 'Class40' ) ,
(DEFAULT,'Demain c’est loin' , 2006 , 'OWEN CLARK' , 'IMOCA' ) ,
(DEFAULT,'Caisses Réunionnaises Complémentaires' , 2021 , 'VPLP' , 'Class40' ) ,
(DEFAULT,'Formatives ESI Business School pour Ocean As Common' , 1990 , 'Philippe HARLÉ' , 'Rhum Mono' ) ,
(DEFAULT,'Médecins du monde' , 2007 , 'Simon Rogers' , 'Class40' ) ,
(DEFAULT,'CAP AU CAP LOCATION' , 1980 , 'Mauric' , 'Rhum Mono' ) ,
(DEFAULT,'Yoda' , 2008, 'Marc Lombard Yacht Design' , 'Class40' ) ,
(DEFAULT,'Dopamine Sailing Team' , 2011  , 'Sam MANUARD' , 'Class40' ) ,
(DEFAULT,'Wisper' , 2010 , 'Guillaume VERDIER' , 'Class40' ) ,
(DEFAULT,'Tradisyon Gwadloup' , 2002 , 'Berret-Racoupeau' , 'Rhum Mono' ) ,
(DEFAULT,'Naviguons contre le diabète' , 2012 , 'Marc Lombard Yacht Design' , 'Class40' ) ,
(DEFAULT,'ACAPELLA - La chaîne de l''espoir' , 1981 , 'Walter Greene' , 'Rhum Multi' ) ,
(DEFAULT,'Château du Launay' , 1982 , 'Dick NEWICK' , 'Rhum Multi' ) ,
(DEFAULT,'Moxie - Bati Armor' , 1979 , 'Dick NEWICK' , 'Rhum Multi' ) ,
(DEFAULT,'HAPPY' , 1980 , 'Walter GREENE' , 'Rhum Multi' ) ,
(DEFAULT,'BLEU BLANC' , 2017 , 'OWEN CLARKE DESIGN' , 'Class40' ) ,
(DEFAULT,'Kornog 2' , 2011 , 'FINOT-CONQ' , 'Rhum Mono' ) ,
(DEFAULT,'Elora' , 2021 , 'Marc Lombard Yacht Design' , 'Class40' ) ,
(DEFAULT,'CAPTAIN ALTERNANCE' , 2021 , 'Marc Lombard Yacht Design' , 'Class40' ) ,
(DEFAULT,'TERRANIMO' , 1999 , 'Berret - Racoupeau Yacht Design' , 'Rhum Mono' ) ,
(DEFAULT,'FAIAOAHE' , 2006 , 'Ribadeau-Dumas' , 'Rhum Mono' ) ,
(DEFAULT,'Bella Donna - Race for Pure Ocean' , 1999 , 'Franco Fineschi' , 'Rhum Mono' ) ,
(DEFAULT,'VIABILIS - PEN DUICK III & ACH Pour les enfants de Robert Debré' , '1967' , 'ERIC TABARLY' , 'Rhum Mono' ) ,
(DEFAULT,'SOS PARE-BRISE +' , 1998 , 'FINOT-CONQ' , 'Rhum Mono' ) ,
(DEFAULT,'JSB Déménagements' , 1994 , 'Farr Yacht Design' , 'Rhum Mono' ) ,
(DEFAULT,'Trilogik - Dys de Coeur' , 2003 , 'LOMBARD ' , 'Rhum Multi' ) ;




CREATE TABLE IF NOT EXISTS P02_resultat(
  skipper_id INTEGER NOT NULL,
  bateau_id INTEGER NOT NULL,
  resultat_pos INTEGER NOT NULL,
  resultat_temps TIME , -- pas de NOT NULL car quelques skippers n'ont pas fini la course mais qui ont tout de meme une position d'arrivée
  FOREIGN KEY (skipper_id) REFERENCES P02_skipper(skipper_id),
  FOREIGN KEY (bateau_id) REFERENCES P02_bateau(bateau_id),
  PRIMARY KEY(skipper_id, bateau_id)
);

INSERT INTO P02_resultat VALUES
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CAUDRELIER' AND skipper_prenom ='Charles'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Maxi Edmond de Rothschild'),1,'163:47:25'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='GABART' AND skipper_prenom ='François'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='SVR-LAZARTIGUE'),2,'167:03:15'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='COVILLE' AND skipper_prenom ='Thomas'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Sodebo Ultim 3'),3,'174:37:25'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='JOYON' AND skipper_prenom ='Francis'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='IDEC Sport'),4,'205:41:40'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE BLEVEC' AND skipper_prenom ='Yves'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='ACTUAL ULTIM 3'),5,'207:49:01'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE VAILLANT' AND skipper_prenom ='Arthur'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='MIEUX'),6,'241:26:51'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE ROUX' AND skipper_prenom ='Erwan'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='KOESIO'),7,'261:35:52'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='VLAMYNCK' AND skipper_prenom ='Quentin'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='ARKEMA'),8,'261:54:05'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE CLÉAC''H' AND skipper_prenom ='Armel'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='MAXI BANQUE POPULAIRE XI'),9,'262:49:24'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ROGUES' AND skipper_prenom ='Sébastien'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Primonial'),10,'267:37:37'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='RUYANT' AND skipper_prenom ='Thomas'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='LinkedOut'),11,'281:36:25'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='PERON' AND skipper_prenom ='Eric'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='KOMILFO'),12,'283:21:30'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DALIN' AND skipper_prenom ='Charlie'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='APIVIA'),13,'283:38:11'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BEYOU' AND skipper_prenom ='Jérémie'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='CHARAL'),14,'285:00:55'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ESCOFFIER' AND skipper_prenom ='Kevin'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Holcim - PRB'),15,'287:31:14'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='TRIPON' AND skipper_prenom ='Armel'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Les P''tits Doudous'),16,'289:38:18'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='SOREL' AND skipper_prenom ='Maxime'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='V and B - Monbana - Mayenne'),17,'296:59:42'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='MEILHAT' AND skipper_prenom ='Paul'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='BIOTHERM'),18,'298:18:33'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='METTRAUX' AND skipper_prenom ='Justine'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='TEAMWORK.NET'),19,'312:26:35'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DUTREUX' AND skipper_prenom ='Benjamin'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Guyot environnement - Water Family'),20,'311:51:24'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='JOSCHKE' AND skipper_prenom ='Isabelle'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='MACSF'),21,'314:26:54'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ATTANASIO' AND skipper_prenom ='Romain'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Fortinet - Best Western'),22,'319:40:20'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='MARSSET' AND skipper_prenom ='Sébastien'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Mon Courtier Energie - Cap Agir Ensemble'),23,'320:36:55'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='HARE' AND skipper_prenom ='Pip'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Medallia'),24,'320:38:12'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LAMIRÉ' AND skipper_prenom ='Gilles'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='GROUPE GCA-1001 SOURIRES'),25,'321:22:23'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE TURQUAIS' AND skipper_prenom ='Tanguy'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='LAZARE'),26,'322:43:44'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='HARAYDA' AND skipper_prenom ='James'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Gentoo Sailing Team'),27,'324:13:35'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='FERRE' AND skipper_prenom ='Benjamin'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Monnoyeur - Duo for a job'),28,'327:39:30'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='PEDOTE' AND skipper_prenom ='Giancarlo'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='PRYSMIAN GROUP'),29,'328:32:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BOISSIERES' AND skipper_prenom ='Arnaud'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='La Mie Câline'),30,'331:37:20'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='COLMAN' AND skipper_prenom ='Conrad'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Imagine'),31,'332:23:08'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BESTAVEN' AND skipper_prenom ='Yannick'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Maître CoQ V'),32,'332:37:27'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='TROUSSEL' AND skipper_prenom ='Nicolas'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='CORUM L''ÉPARGNE'),33,'332:57:02'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ROURA' AND skipper_prenom ='Alan'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Hublot'),34,'337:47:13'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='RICHOMME' AND skipper_prenom ='Yoann'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Paprec Arkéa'),35,'339:08:40'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BECCARIA' AND skipper_prenom ='Ambrogio'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='ALLAGRANDE PIRELLI'),36,'343:23:48'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CORNIC' AND skipper_prenom ='Antoine'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='HUMAN Immobilier'),37,'336:34:25'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DOUGUET' AND skipper_prenom ='Corentin'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='QUEGUINER - INNOVEO'),38,'345:24:12'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BELLION' AND skipper_prenom ='Eric'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='COMMEUNSEULHOMME Powered by Altavia'),39,'349:26:40'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='HERRMANN' AND skipper_prenom ='Boris'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Malizia - Seaexplorer'),40,'351:21:41'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='KOSTER' AND skipper_prenom ='Simon'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Banque du Leman'),41,'354:45:00'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='SOUDEE' AND skipper_prenom ='Guirec'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='FREELANCE.COM'),42,'352:58:48'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CARPENTIER' AND skipper_prenom ='Antoine'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Redman'),43,'358:10:45'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='MACAIRE' AND skipper_prenom ='Xavier'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Groupe SNEF'),44,'358:18:20'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='WEÖRES' AND skipper_prenom ='Szabolcs'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Szabi Racing'),45,'358:19:14'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BERRY' AND skipper_prenom ='Luke'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Lamotte - Module Création'),46,'359:00:22'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DUC' AND skipper_prenom ='Louis'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Fives - Lantana Environnement'),47,'365:19:07'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BONA' AND skipper_prenom ='Alberto'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='IBSA'),48,'366:19:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='PILLIARD' AND skipper_prenom ='Romain'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Use It Again! by Extia'),49,'383:26:28'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE PAPE' AND skipper_prenom ='Martin'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Fondation Stargardt'),50,'388:30:04'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DAVIES' AND skipper_prenom ='Samantha'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='INITIATIVES COEUR'),51,'390:35:17'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ESCOFFIER' AND skipper_prenom ='Loïc'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='LODIGROUP'),52,'390:37:23'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='JOURDAIN' AND skipper_prenom ='Roland'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='We Explore'),53,'391:21:00'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='XU' AND skipper_prenom ='Jingkun'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='China Dream•Haikou'),54,'392:34:00'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='TRÉHIN' AND skipper_prenom ='Axel'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Project Rescue Ocean'),55,'393:01:16'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DE PAVANT' AND skipper_prenom ='Kito'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='HBF - Reforest''Action'),56,'396:00:45'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='COUSIN' AND skipper_prenom ='Manuel'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Groupe SÉTIN'),57,'397:08:05'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE ROCH' AND skipper_prenom ='Emmanuel'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Edenred'),58,'397:20:25'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DICK' AND skipper_prenom ='Jean-Pierre'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Notre Méditerranée - Ville de Nice'),59,'397:57:51'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LIPINSKI' AND skipper_prenom ='Ian'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='CRÉDIT MUTUEL'),60,'398:08:46'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='MEHRAN' AND skipper_prenom ='Alex'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Polka Dot'),61,'398:56:15'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='GUILLEMOT' AND skipper_prenom ='Marc'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='METAROM MG5'),62,'401:51:06'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='GUIFFANT' AND skipper_prenom ='François'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Kattan'),63,'403:06:40'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='MABIRE' AND skipper_prenom ='Halvard'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='GDD'),64,'404:00:26'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='D''ESTAIS' AND skipper_prenom ='Nicolas'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='HappyVore - Café Joyeux'),65,'405:07:10'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='MATHELIN - MOREAUX' AND skipper_prenom ='William'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Dékuple'),66,'407:23:08'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='HEER' AND skipper_prenom ='Oliver'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Oliver Heer Ocean Racing'),67,'408:22:55'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BONNIER' AND skipper_prenom ='Jules'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Nestenn - Entrepreneurs pour la Planète'),68,'408:55:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='HULIN' AND skipper_prenom ='Baptiste'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Parenthèses de Vies'),69,'413:52:19'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CHATEAU' AND skipper_prenom ='Cédric'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='SOGESTRAN - SEAFRIGO'),70,'414:34:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LEPESQUEUX' AND skipper_prenom ='Marc'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='CURIUM life forward'),71,'415:43:23'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='FORNARO' AND skipper_prenom ='Andrea'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='INFLUENCE'),72,'418:30:46'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CHAPALAIN' AND skipper_prenom ='Gwen'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Guyader - Savéol'),73,'421:19:15'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DARAMY' AND skipper_prenom ='Jean-Baptiste'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Chocolats Paries - Screb'),74,'426:01:30'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE VOURCH' AND skipper_prenom ='Didier'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='VICITAN'),75,'439:01:35'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LE BORGNE' AND skipper_prenom ='Kieran'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Recycleurs Bretons'),76,'439:43:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='SEPHO' AND skipper_prenom ='Rodolphe'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Rêve de Large - Region Guadeloupe'),77,'447:02:17'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='PAYEN' AND skipper_prenom ='Fabrice'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Ille et Vilaine Cap vers l''inclusion'),78,'448:26:59'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='THURET' AND skipper_prenom ='Stan'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='EVERIAL'),79,'449:48:03'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CASENAVE-PÉRÉ' AND skipper_prenom ='Pierre'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Legallais'),80,'450:34:04'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='POUPON' AND skipper_prenom ='Philippe'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Flo'),81,'451:03:37'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='HOCHEDE' AND skipper_prenom ='Etienne'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='PiR2'),82,'461:03:54'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ATTWELL' AND skipper_prenom ='Pierre-Louis'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='VOGUE AVEC UN CROHN'),83,'461:10:36'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CLAVEAU' AND skipper_prenom ='Mathieu'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Prendre la mer, Agir pour la Forêt'),84,'462:39:05'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LEONARD' AND skipper_prenom ='Greg'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Kite'),85,'463:41:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ROUGER' AND skipper_prenom ='Nicolas'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Demain c’est loin'),86,'464:17:42'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='JOST' AND skipper_prenom ='Victor'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Caisses Réunionnaises Complémentaires'),87,'464:40:40'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CHABAUD' AND skipper_prenom ='Catherine'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Formatives ESI Business School pour Ocean As Common'),88,'466:18:43'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='URSAULT POUPON' AND skipper_prenom ='Morgane'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Médecins du monde'),89,'466:56:54'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CLERTON' AND skipper_prenom ='Wilfrid'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='CAP AU CAP LOCATION'),90,'478:11:45'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BOUVET' AND skipper_prenom ='Franz'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Yoda'),91,'480:33:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='GUEGUEN' AND skipper_prenom ='Florian'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Dopamine Sailing Team'),92,'489:42:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CAUWE' AND skipper_prenom ='Maxime'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Wisper'),93,'499:02:50'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BISSAINTE' AND skipper_prenom ='Willy'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Tradisyon Gwadloup'),94,'500:59:10'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='FACON' AND skipper_prenom ='Anatole'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Naviguons contre le diabète'),95,'504:04:34'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='CAPELLE' AND skipper_prenom ='Charlie'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='ACAPELLA - La chaîne de l''espoir'),96,'511:56:24'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BOGRAND' AND skipper_prenom ='Christophe'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Château du Launay'),97,'512:50:35'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='LURTON' AND skipper_prenom ='Thomas'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Moxie - Bati Armor'),98,'524:09:20'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ETHEIMER' AND skipper_prenom ='Laurent'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='HAPPY'),99,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='THOMAS' AND skipper_prenom ='Hervé'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='BLEU BLANC'),100,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='COLUBI' AND skipper_prenom ='Gilles'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Kornog 2'),101,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='NEMSGUERN' AND skipper_prenom ='Olivier'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Elora'),102,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='PIPEROL' AND skipper_prenom ='Keni'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='CAPTAIN ALTERNANCE'),103,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='PRONIER' AND skipper_prenom ='Guy'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='TERRANIMO'),104,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='GERIN' AND skipper_prenom ='Remy'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='FAIAOAHE'),105,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='GENNARI' AND skipper_prenom ='Fabio'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Bella Donna - Race for Pure Ocean'),106,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='PENNARUN' AND skipper_prenom ='Arnaud'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='VIABILIS - PEN DUICK III & ACH Pour les enfants de Robert Debré'),107,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='ECALARD' AND skipper_prenom ='Daniel'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='SOS PARE-BRISE +'),108,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='BIARD' AND skipper_prenom ='Jean-Sébastien'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='JSB Déménagements'),109,'NULL'),
((SELECT skipper_id FROM P02_skipper WHERE skipper_nom ='DUCOSSON' AND skipper_prenom ='David'), (SELECT bateau_id FROM P02_bateau WHERE bateau_nom ='Trilogik - Dys de Coeur'),110,'NULL');
